[package]
name = "rustblog"
version = "0.1.0"
authors = ["raphaelsoul <raphaelsoul@163.com>"]

[[bin]]
name = "guess"
path = "src/guess.rs"

[[bin]]
name = "http"
path = "src/http.rs"

[dependencies]
rand = "0.3.14"
